version: '3.1'
services:
  redis:
    image: redis:6-alpine

    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
  bot:
    build: .
    links:
      - redis
    container_name: 'bot'

    restart: on-failure
    environment:
      DISCORD_BOT_TOKEN: 'Токен'
      DISCORD_BOT_GUILD: 'ID гильдии'
      REDISHOST: 'redis'
