version: '3.1'
services:
  redis:
    image: redis:6-alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

  postgres:
    build: docker/postgres
    environment:
      POSTGRES_USER: 'yuudachi'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'yuudachi'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
